version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:25"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
